### ISSUE TITLE
Output for auto incorrect

### ISSUE THREAD

**Issue by icco** [Soitora/PlexAniSync-Mapping-Assistant#43]
With `config/default.yaml` set to 

```
userConfig:
  preferMetadata: "tmdb" # Possible values: `tmdb`, `tvdb`.
  preferMedia: "tv" # Possible values: `tv`, `movie`.
  copyResults: false # Possible values: `true`, `false`.
  saveResults: true # Possible values: `true`, `false`.
  dualOutput: false # Possible values: `true`, `false`.
  inputFilePath: "batch/input.txt" # A valid path to a TXT input file, see the README example.
  outputFilePath: "batch/output/" # A valid path for the output YAML files, see the README example.
```

With `TMDB_APIKEY`, `PLEX_HOST` and `PLEX_TOKEN` correctly set.

npm run test passes

<img width="651" alt="Screenshot 2025-01-12 at 20 19 51" src="https://github.com/user-attachments/assets/57324de8-87e9-4827-b6c4-8b0dce18a677" />

but with `batch/input.txt` set to

```
247367
207332
```

I get the following `batch/output/series-tmdb.en.yaml`

```
[object Object]
[object Object]
```

Running on version db074d5d633905f122dc5f14833a13c27b89e34a
